-- AlterTable
ALTER TABLE "ClientMaster" ADD COLUMN     "contactNumber" TEXT,
ADD COLUMN     "contactPerson" TEXT,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "sameAsBilling" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "InspectionJob" ADD COLUMN     "clientId" TEXT,
ADD COLUMN     "deadline" TIMESTAMP(3),
ADD COLUMN     "itemId" TEXT;

-- AlterTable
ALTER TABLE "InspectionLot" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Packet" ADD COLUMN     "packetWeight" DOUBLE PRECISION,
ADD COLUMN     "submittedToRndAt" TIMESTAMP(3),
ADD COLUMN     "submittedToRndBy" TEXT;

-- AlterTable
ALTER TABLE "Sample" ADD COLUMN     "homogeneousProofDone" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "SampleSealLabel" ADD COLUMN     "editableByAdminOnly" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "sealSource" TEXT DEFAULT 'MANUAL';

-- CreateTable
CREATE TABLE "ContainerTypeMaster" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ContainerTypeMaster_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ModuleWorkflowSettings" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "autoLotNumbering" BOOLEAN NOT NULL DEFAULT false,
    "lotNumberPrefix" TEXT,
    "lotNumberSequenceFormat" TEXT,
    "autoSampleIdGeneration" BOOLEAN NOT NULL DEFAULT true,
    "sampleIdPrefix" TEXT,
    "sampleIdSequenceFormat" TEXT,
    "finalDecisionApproverPolicy" TEXT NOT NULL DEFAULT 'MANAGER_ADMIN',
    "lockPacketEditingAfterRndSubmit" BOOLEAN NOT NULL DEFAULT true,
    "sealScanRequired" BOOLEAN NOT NULL DEFAULT true,
    "imageTimestampRequired" BOOLEAN NOT NULL DEFAULT false,
    "requiredImageCategories" TEXT[],
    "optionalImageCategories" TEXT[],
    "bulkSealGenerationEnabled" BOOLEAN NOT NULL DEFAULT true,
    "sealEditPolicy" TEXT NOT NULL DEFAULT 'ADMIN_ONLY',
    "containerTypeSource" TEXT NOT NULL DEFAULT 'MASTER_ONLY',
    "homogeneousProofRequired" BOOLEAN NOT NULL DEFAULT true,
    "packetPurposeMode" TEXT NOT NULL DEFAULT 'OPTIONAL',
    "showOptionalImageSection" BOOLEAN NOT NULL DEFAULT true,
    "showBlockersInline" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ModuleWorkflowSettings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ContainerTypeMaster_companyId_idx" ON "ContainerTypeMaster"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "ContainerTypeMaster_companyId_name_key" ON "ContainerTypeMaster"("companyId", "name");

-- CreateIndex
CREATE UNIQUE INDEX "ModuleWorkflowSettings_companyId_key" ON "ModuleWorkflowSettings"("companyId");
