export type PublicUser = {
  id?: string;
  email?: string | null;
  role: "ADMIN" | "OPERATIONS" | "RND" | "VIEWER";
  profile: {
    displayName: string;
    companyName?: string | null;
    jobTitle?: string | null;
    avatarUrl?: string | null;
  } | null;
};

export type InspectionJob = {
  id: string;
  inspectionSerialNumber: string;
  companyId: string;
  jobReferenceNumber: string | null;
  clientName: string;
  clientId?: string | null;
  commodity: string;
  itemId?: string | null;
  materialType?: "INHOUSE" | "TRADED" | string | null;
  plantLocation?: string | null;
  deadline?: string | Date | null;
  status: string;
  createdByUserId: string;
  assignedToId?: string | null;
  assignedById?: string | null;
  assignedAt?: string | Date | null;
  jobStartedAt?: string | Date | null;
  sentToAdminAt?: string | Date | null;
  sentToAdminBy?: string | null;
  adminDecisionAt?: string | Date | null;
  adminDecisionBy?: string | null;
  adminDecisionStatus?: "PASS" | "HOLD" | "REJECT" | string | null;
  operationsCompletedAt?: string | Date | null;
  handedOverToRndAt?: string | Date | null;
  handedOverToRndBy?: string | null;
  handedOverToRndTo?: string | null;
  createdAt: string | Date;
  updatedAt: string | Date;
  assignedTo?: PublicUser | null;
  assignedBy?: PublicUser | null;
  createdByUser?: PublicUser | null;
  lots?: InspectionLot[];
  auditLogs?: AuditLog[];
  reportSnapshots?: ReportSnapshot[];
  mediaFiles?: InspectionMediaFile[];
};


export type InspectionLot = {
  id: string;
  jobId: string;
  companyId?: string;
  lotNumber: string;
  isAutoGenerated?: boolean;
  materialName?: string | null;
  materialCategory?: string | null;
  quantityMode?: "SINGLE_PIECE" | "MULTI_WEIGHT" | string | null;
  bagCount?: number | null;
  pieceCount?: number | null;
  weightUnit?: string | null;
  remarks?: string | null;
  totalBags: number;
  grossWeightKg?: number | null;
  netWeightKg?: number | null;
  grossWeight?: number | null;
  tareWeight?: number | null;
  netWeight?: number | null;
  sealNumber?: string | null;
  sealAuto?: boolean;
  bagPhotoUrl?: string | null;
  samplingPhotoUrl?: string | null;
  sealPhotoUrl?: string | null;
  status?: string;
  assignedToId?: string | null;
  assignedById?: string | null;
  assignedAt?: string | Date | null;
  createdAt: string | Date;
  updatedAt?: string | Date;
  assignedTo?: PublicUser | null;
  assignedBy?: PublicUser | null;
  sampling?: Sampling | Sampling[] | null;
  sample?: SampleRecord | null;
  bags?: InspectionBag[];
  mediaFiles?: InspectionMediaFile[];
  inspection?: LotInspectionRecord | null;
};

export type InspectionMediaCategory =
  | "BAG"
  | "SEAL"
  | "BEFORE"
  | "DURING"
  | "AFTER"
  | "BAG_WITH_LOT_NO"
  | "MATERIAL_VISIBLE"
  | "SAMPLING_IN_PROGRESS"
  | "SEALED_BAG"
  | "SEAL_CLOSEUP"
  | "BAG_CONDITION"
  | "DAMAGE_PHOTO"
  | "HOMOGENEOUS"
  | "LOT_OVERVIEW"
  | "BAG_CLOSEUP"
  | "LABEL_CLOSEUP"
  | "INSPECTION_IN_PROGRESS"
  | "CONTAMINATION_PHOTO";

export type InspectionMediaFile = {
  id: string;
  lotId?: string | null;
  jobId?: string | null;
  inspectionId?: string | null;
  inspectionIssueId?: string | null;
  category: InspectionMediaCategory | string;
  storageKey: string;
  fileName: string;
  createdAt: string | Date;
};

export type InspectionDecisionStatus =
  | "PENDING"
  | "READY_FOR_SAMPLING"
  | "ON_HOLD"
  | "REJECTED";

export type InspectionStatus = "IN_PROGRESS" | "COMPLETED";

export type InspectionChecklistItem = {
  id: string;
  itemKey: string;
  sectionName: string;
  itemLabel: string;
  responseType: string;
  isRequired: boolean;
  materialCategory?: string | null;
  displayOrder: number;
  isActive: boolean;
};

export type InspectionChecklistResponse = {
  id: string;
  inspectionId: string;
  checklistItemMasterId: string;
  sectionName: string;
  itemLabel: string;
  responseValue?: string | null;
  responseText?: string | null;
  isException: boolean;
  displayOrder: number;
  recordedAt: string | Date;
  checklistItemMaster?: InspectionChecklistItem | null;
};

export type InspectionIssue = {
  id: string;
  inspectionId: string;
  issueCategory: string;
  severity: "MINOR" | "MODERATE" | "CRITICAL" | string;
  description: string;
  status: string;
  createdAt: string | Date;
  updatedAt?: string | Date;
};

export type LotInspectionRecord = {
  id: string;
  jobId: string;
  lotId: string;
  inspectorId: string;
  inspectionStatus: InspectionStatus | string;
  decisionStatus: InspectionDecisionStatus | string;
  startedAt: string | Date;
  sentToAdminAt?: string | Date | null;
  sentToAdminBy?: string | null;
  decisionAt?: string | Date | null;
  decisionBy?: string | null;
  decisionOutcome?: "PASS" | "HOLD" | "REJECT" | string | null;
  completedAt?: string | Date | null;
  overallRemark?: string | null;
  identityRiskFlag: boolean;
  packagingRiskFlag: boolean;
  materialRiskFlag: boolean;
  samplingBlockedFlag: boolean;
  issueCount: number;
  createdAt: string | Date;
  updatedAt: string | Date;
  responses?: InspectionChecklistResponse[];
  issues?: InspectionIssue[];
  mediaFiles?: InspectionMediaFile[];
};

export type InspectionBag = {
  id: string;
  lotId: string;
  bagNumber: number;
  grossWeight?: number | null;
  netWeight?: number | null;
  createdAt: string | Date;
};

export type Sampling = {
  id: string;
  lotId: string;
  companyId?: string;
  beforePhotoUrl?: string | null;
  duringPhotoUrl?: string | null;
  afterPhotoUrl?: string | null;
  status?: string;
  assignedToId?: string | null;
  assignedById?: string | null;
  assignedAt?: string | Date | null;
  createdAt: string | Date;
  assignedTo?: PublicUser | null;
  assignedBy?: PublicUser | null;
};

export type SampleEventType =
  | "SAMPLE_CREATED"
  | "SAMPLE_COLLECTED"
  | "DETAILS_CAPTURED"
  | "HOMOGENIZED"
  | "SEALED"
  | "LABELED"
  | "READY_FOR_PACKETING";

export type SampleMediaType =
  | "SAMPLING_IN_PROGRESS"
  | "SAMPLE_CONTAINER"
  | "SAMPLE_LABEL"
  | "SEALED_SAMPLE"
  | "HOMOGENIZED_SAMPLE"
  | "SAMPLE_CONDITION";

export type SampleRecord = {
  id: string;
  companyId: string;
  jobId: string;
  lotId: string;
  inspectionId: string;
  sampleCode: string;
  sampleStatus: string;
  sampleType?: string | null;
  samplingMethod?: string | null;
  samplingDate?: string | Date | null;
  sampleQuantity?: number | null;
  sampleUnit?: string | null;
  containerType?: string | null;
  remarks?: string | null;
  homogeneousProofDone?: boolean;
  homogenizedAt?: string | Date | null;
  readyForPacketingAt?: string | Date | null;
  createdById: string;
  createdAt: string | Date;
  updatedAt?: string | Date;
  events?: SampleEventRecord[];
  media?: SampleMediaRecord[];
  sealLabel?: SampleSealLabelRecord | null;
  packets?: PacketRecord[];
  createdBy?: PublicUser | null;
};

export type SampleEventRecord = {
  id: string;
  sampleId: string;
  eventType: SampleEventType | string;
  eventTime: string | Date;
  performedById?: string | null;
  remarks?: string | null;
  metadata?: Record<string, unknown> | null;
  createdAt: string | Date;
  performedBy?: PublicUser | null;
};

export type SampleMediaRecord = {
  id: string;
  sampleId: string;
  mediaType: SampleMediaType | string;
  fileUrl: string;
  capturedAt: string | Date;
  capturedById?: string | null;
  remarks?: string | null;
  createdAt: string | Date;
  capturedBy?: PublicUser | null;
};

export type SampleSealLabelRecord = {
  id: string;
  sampleId: string;
  sealNo?: string | null;
  labelText?: string | null;
  sealStatus?: string | null;
  sealSource?: string | null;
  editableByAdminOnly?: boolean;
  labeledAt?: string | Date | null;
  sealedAt?: string | Date | null;
  createdAt: string | Date;
  updatedAt?: string | Date;
};

export type HomogeneousSample = {
  id: string;
  jobId: string;
  photoUrl?: string | null;
  createdAt: string | Date;
  packets?: SamplePacket[];
};

export type PacketEventType =
  | "PACKET_CREATED"
  | "PACKET_LABELED"
  | "PACKET_SEALED"
  | "PACKET_VERIFIED"
  | "PACKET_ASSIGNED_TO_TRIAL"
  | "PACKET_RELEASED"
  | "PACKET_MARKED_USED";

export type PacketMediaType =
  | "PACKET_LABEL"
  | "PACKET_SEALED"
  | "PACKET_CONDITION"
  | "PACKET_GROUP_VIEW";

export type PacketAllocationStatus = "AVAILABLE" | "RESERVED" | "ALLOCATED" | "USED" | "BLOCKED";

export type PacketRecord = {
  id: string;
  companyId?: string;
  jobId?: string;
  lotId?: string;
  sampleId: string;
  packetNo: number;
  packetCode: string;
  packetStatus: string;
  packetQuantity?: number | null;
  packetWeight?: number | null;
  packetUnit?: string | null;
  packetType?: string | null;
  remarks?: string | null;
  readyAt?: string | Date | null;
  submittedToRndAt?: string | Date | null;
  submittedToRndBy?: string | null;
  createdById?: string;
  createdAt: string | Date;
  updatedAt?: string | Date;
  sealLabel?: PacketSealLabelRecord | null;
  media?: PacketMediaRecord[];
  events?: PacketEventRecord[];
  allocation?: PacketAllocationRecord | null;
  sample?: Pick<SampleRecord, "id" | "sampleCode" | "sampleQuantity" | "sampleUnit"> | null;
  lot?: Pick<InspectionLot, "id" | "lotNumber" | "materialName"> | null;
};

export type SamplePacket = PacketRecord;

export type PacketEventRecord = {
  id: string;
  packetId: string;
  eventType: PacketEventType | string;
  eventTime: string | Date;
  performedById?: string | null;
  remarks?: string | null;
  metadata?: Record<string, unknown> | null;
  createdAt: string | Date;
  performedBy?: PublicUser | null;
};

export type PacketMediaRecord = {
  id: string;
  packetId: string;
  mediaType: PacketMediaType | string;
  fileUrl: string;
  capturedAt: string | Date;
  capturedById?: string | null;
  remarks?: string | null;
  createdAt: string | Date;
  capturedBy?: PublicUser | null;
};

export type PacketSealLabelRecord = {
  id: string;
  packetId: string;
  sealNo?: string | null;
  labelText?: string | null;
  labelCode?: string | null;
  sealStatus?: string | null;
  sealedAt?: string | Date | null;
  labeledAt?: string | Date | null;
  createdAt: string | Date;
  updatedAt?: string | Date;
};

export type PacketAllocationRecord = {
  id: string;
  packetId: string;
  allocationStatus: PacketAllocationStatus | string;
  allocatedToType?: string | null;
  allocatedToId?: string | null;
  allocatedAt?: string | Date | null;
  createdAt: string | Date;
  updatedAt?: string | Date;
};

export type PacketUsageLedgerEntryType =
  | "ALLOCATE"
  | "CONSUME"
  | "RELEASE"
  | "RECLASSIFY"
  | "ADJUST";

export type PacketUsageLedgerDirection = "IN" | "OUT";

export type PacketUsageLedgerEntry = {
  id: string;
  packetId: string;
  rndJobId?: string | null;
  entryType: PacketUsageLedgerEntryType;
  useType?: string | null;
  quantity: number;
  unit: string;
  direction: PacketUsageLedgerDirection;
  notes?: string | null;
  createdById: string;
  createdAt: string | Date;
};

export type PacketUsageBalance = {
  available: number;
  reserved: number;
  consumed: number;
  retained: number;
  backup: number;
  reference: number;
  clientRetest: number;
  additionalAnalysis: number;
};

export type ResultPrecedenceStatus = "ACTIVE" | "SUPERSEDED";

export type RndRetestCreateRequest = {
  sourceRndJobId: string;
  packetId: string;
  requestedQty: number;
  useType: "TESTING" | "RETAIN" | "BACKUP" | "REFERENCE" | "CLIENT_RETEST" | "ADDITIONAL_ANALYSIS";
  reason: string;
};

export type RDTrial = {
  id: string;
  trialNumber: number;
  lotId?: string | null;
  packetId?: string | null;
  packet?: SamplePacket | null;
  measurements: RDMeasurement[];
};

export type RDMeasurement = {
  id: string;
  element: string;
  value: number;
};

export type ReportSnapshot = {
  id: string;
  jobId: string;
  data: Record<string, unknown>; // Complex JSON data
  createdAt: string | Date;
};

export type AuditLog = {
  id: string;
  jobId: string;
  userId: string;
  entity?: string;
  action: string;
  from?: string | null;
  to?: string | null;
  notes?: string | null;
  metadata?: Record<string, unknown> | null;
  createdAt: string | Date;
  user?: PublicUser | null;
};

export type RndJobStatus =
  | "CREATED"
  | "READY_FOR_TEST_SETUP"
  | "READY_FOR_TESTING"
  | "IN_TESTING"
  | "AWAITING_REVIEW"
  | "APPROVED"
  | "COMPLETED"
  | "REWORK_REQUIRED";

export type RndJobType =
  | "INITIAL_TEST"
  | "RETEST"
  | "CLIENT_REQUESTED_RETEST"
  | "BACKUP_TEST"
  | "RETAIN_TEST";

export type RndReviewAction = "APPROVE" | "REJECT" | "REWORK";

export type RndJobReading = {
  id: string;
  rndJobId: string;
  parameter: string;
  value: number;
  unit?: string | null;
  remarks?: string | null;
  createdAt: string | Date;
  updatedAt?: string | Date;
};

export type RndJobAttachment = {
  id: string;
  rndJobId: string;
  fileName: string;
  fileUrl: string;
  mimeType?: string | null;
  fileSizeBytes?: number | null;
  notes?: string | null;
  uploadedById?: string | null;
  uploadedBy?: PublicUser | null;
  createdAt: string | Date;
  updatedAt?: string | Date;
};

export type RndJobReview = {
  id: string;
  rndJobId: string;
  action: RndReviewAction;
  notes?: string | null;
  reviewedById: string;
  reviewedBy?: PublicUser | null;
  reviewedAt: string | Date;
  createdAt: string | Date;
};

export type RndJobRecord = {
  id: string;
  rndJobNumber: string;
  companyId: string;
  parentJobId: string;
  lotId: string;
  sampleId: string;
  packetId: string;
  previousRndJobId?: string | null;
  status: RndJobStatus;
  jobType: RndJobType;
  packetUse?: string | null;
  testType?: string | null;
  testMethod?: string | null;
  priority?: string | null;
  deadline?: string | Date | null;
  assignedToId?: string | null;
  approverUserId?: string | null;
  remarks?: string | null;
  receivedAt: string | Date;
  testingStartedAt?: string | Date | null;
  resultsSubmittedAt?: string | Date | null;
  reviewedAt?: string | Date | null;
  completedAt?: string | Date | null;
  createdAt: string | Date;
  updatedAt?: string | Date;
  parentJob?: Pick<InspectionJob, "id" | "inspectionSerialNumber" | "jobReferenceNumber" | "status"> | null;
  lot?: Pick<InspectionLot, "id" | "lotNumber" | "materialName"> | null;
  sample?: Pick<SampleRecord, "id" | "sampleCode" | "sampleStatus" | "sampleType"> | null;
  packet?: Pick<PacketRecord, "id" | "packetCode" | "packetWeight" | "packetUnit" | "packetType"> | null;
  assignedTo?: PublicUser | null;
  approverUser?: PublicUser | null;
  previousRndJob?: Pick<RndJobRecord, "id" | "rndJobNumber" | "status" | "jobType"> | null;
  nextRetestJobs?: Array<Pick<RndJobRecord, "id" | "rndJobNumber" | "status" | "jobType" | "createdAt">>;
  readings?: RndJobReading[];
  attachments?: RndJobAttachment[];
  reviews?: RndJobReview[];
};
